spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
        format_sql: true
        show_sql: true

API:
  Fedex:
    grant_type: client_credentials
    client_id: ${Fedex_ClientId}
    client_secret: ${Fedex_ClientSecret}

jwt:
  secret-key: ${jwt_key}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}       # IAM AccessKey
      secretKey: ${AWS_SECRET_ACCESS_KEY}   # IAM SecretKey
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false